FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Install system dependencies (dibutuhkan cassandra-driver)
RUN apt-get update && apt-get install -y \
    gcc \
    libev-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first (cache friendly)
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY consumer2.py .

# Run consumer
CMD ["python", "consumer2.py"]
